remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache


# Site settings
title: ""  # This appears in the header/browser tab
name: ""   # This replaces your username in various places
author:
  name: "LZ" # For author bylines

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages
