remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache


# Site settings
title: "Lele Zhao"  # This appears in the header/browser tab
name: "Lele Zhao"   # This replaces your username in various places
author:
  name: "Lele Zhao" # For author bylines
